---
name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.0'

    - name: Build
      run: hugo
      # run: hugo -t hugo-theme-learn

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      #env:
      #  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ansible-labs-crew/ansible-labs-crew.github.io
        publish_branch: master
        publish_dir: ./public
